# Generated by Django 4.1.5 on 2023-01-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_products_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.TextField(default='StoreType'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_max',
            field=models.TextField(default='PriceMax'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_min',
            field=models.TextField(default='PriceMin'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sold',
            field=models.TextField(default='HistoricalSold'),
        ),
    ]
