# Generated by Django 4.1.5 on 2023-01-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_products_store_alter_products_price_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='time',
        ),
    ]
