# Generated by Django 4.1.5 on 2023-01-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_products_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='link',
            field=models.TextField(default='Link'),
        ),
    ]
